In [1]:
import tensorflow as tf
import numpy as np

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

`x_train` og `x_test` er begge to billeder af håndskrevne tal. `y_test` og `y_train` er de rigtige værdier for hvert tal

forskellen på train og test er at train dataen skal bruges mens det neurale netværk lærer og test bliver brugt til at evaluere hvor godt netværket er. Siden netværket aldrig har set disse eksempler før så kan dette vise hvor godt netværket fungere på ukendt data uden at den kan overfitte.

In [3]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

Nu skal netværket defineres, det her er altså hvilke lag dataen skal igennem, her skal man også definere hvordan input data ser ud

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

Her efter prøver vi at kører modellen vi lige har defineret, på det første billede i vores trænings data. outputtet herfra er vores 10 nodes som vi definerede i vores netværk struktur set over

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.16535282,  0.08182858,  0.23794667,  0.4743528 ,  0.47873574,
         0.03385592, -0.21421972, -0.23677854, -0.32489166, -0.02790954]],
      dtype=float32)

Det her data er mest af alt ubrugeligt siden netværket ikke er trænet endnu og derfor bare spytter tilfældige værdier ud. Men hvert tal her svarer til hvad netværket tror tallet er fra 0-9

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07885799, 0.10097067, 0.1180311 , 0.14950866, 0.15016538,
        0.09624119, 0.07509708, 0.07342195, 0.06722935, 0.09047667]],
      dtype=float32)

Vi kan bruge softmax til at lave disse tal om til en procent der svarer til hvor stor procent netværket tror det er svaret

Nu skal der vælges en loss funktion. Her bruger vi SparseCategoricalCrossentropy siden vi har flere kategorier, hvis vi havde 2 valg sandt eller falsk ville man nok bruge binarycrossentropy 

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Nu hvor vi har en loss fn så kan vi prøve at teste de tidligere predictions med mærkattet fra data sættet.

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.3408978

Nu har vi prøvet det hele af, så nu skal modellen bare trænes. Her kan vælge i mellem mange forskellige algoritmer, her burger vi bare adam. Metrics skal bare være accuracy med mindre man gør noget mærkeligt

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Så starter vi trænningen med vores trænings data

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2984 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1462 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1106 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0901 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0767 - accuracy: 0.9758


Nu hvor modellen er trænet kan vi finde ud af hvor god den er

In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0769 - accuracy: 0.9759 - 322ms/epoch - 1ms/step


[0.07687602192163467, 0.9758999943733215]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0338330e-07, 5.1836340e-09, 6.5386293e-06, 1.3139765e-04,
        1.8055530e-12, 1.1917374e-06, 4.9531180e-14, 9.9985814e-01,
        6.2987408e-07, 2.0451096e-06],
       [2.6960418e-09, 8.5740787e-05, 9.9990129e-01, 1.1792849e-05,
        1.9633228e-13, 1.0450751e-06, 2.3839775e-09, 3.1142008e-13,
        1.4055037e-07, 4.6210038e-14],
       [1.0778501e-06, 9.9758279e-01, 2.0820716e-04, 1.3445839e-04,
        1.0964774e-05, 2.6997212e-05, 5.8267919e-06, 1.4382901e-03,
        5.8356812e-04, 7.8728599e-06],
       [9.9980670e-01, 1.2216687e-11, 6.0954961e-05, 1.3395494e-07,
        2.7682168e-07, 1.5158237e-05, 1.1403263e-04, 9.0104908e-07,
        1.3221576e-09, 1.9540662e-06],
       [6.2404126e-07, 4.4980226e-08, 1.3313356e-05, 5.9294490e-07,
        9.9741024e-01, 4.2079762e-08, 9.3958664e-07, 9.2096889e-05,
        1.5024169e-07, 2.4820683e-03]], dtype=float32)>